-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
      -   id: black
          language_version: python3.7
-   repo: https://gitlab.com/pycqa/flake8
    rev: 'master'  # pick a git hash / tag to point to
    hooks:
      -   id: flake8
